### PR TITLE
[Calendar] Add Exception Handling, Code Refine, Add More Tests

### LINKED ISSUE #413: Exception handling for Calendar Skill with GraphAPI
**Project**
Virtual Assistant, Skills

**Description**
Need to properly handle exceptions for Calendar Skill with GraphAPI calls

### LINKED ISSUE #414: Exception handling for Calendar Skill with Google Calendar
**Project**
Virtual Assistant, Skills

**Description**
Need to properly handle exceptions for Calendar Skill with GraphAPI calls

### PR DESCRIPTION
**Pull request by Theodosia1005**
## Description

Refine namespace.
refine test mock client interface.
Add exception handling
Add some more tests

## Related Issue

fixes #413
fixes #414

## Checklist
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the appropriate unit tests
- [ ] I have updated related documentation

If this contains changes that needs to be replicated between the Enterprise Template <-> Virtual Assistant
- [ ] A duplicate issue is filed to track future  work.

If you have updated responses or `.lu` files:
- [ ] All languages have been updated
- [ ] You have tested deployment with your new models

### CODE REVIEW

File: solutions/Virtual-Assistant/src/csharp/skills/tests/CalendarSkillTest/API/Fakes/MockGoogleClient/MockGoogleUserClient.cs [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+
+namespace CalendarSkillTest.API.Fakes.MockGoogleClient
+{
+    public static class MockGoogleUserClient
+    {
+        private static Mock<PeopleService> mockGoogleUserService;
+        private static Mock<PeopleResource> mockPeopleResource;
+        private static Mock<ConnectionsResource> mockConnectionsResource;
+
+        static MockGoogleUserClient()
```
Comment (lzc850612) [inline solutions/Virtual-Assistant/src/csharp/skills/tests/CalendarSkillTest/API/Fakes/MockGoogleClient/MockGoogleUserClient.cs]: public static

if you don't specify by default it's internal. it could cause weird problem when we don't notice so it's better to specify explicitly

Comment (lzc850612) [reply solutions/Virtual-Assistant/src/csharp/skills/tests/CalendarSkillTest/API/Fakes/MockGoogleClient/MockGoogleUserClient.cs]: can you change this for all other existing code as well? I noticed that for instancfor instance MockGoogleServiceClient.cs has the same issue.

File: solutions/Virtual-Assistant/src/csharp/skills/tests/CalendarSkillTest/Flow/Strings/Strings.cs [hunk 2]
```diff
@@ -37,5 +37,7 @@ public class Strings
         public static string UserEmailAddress { get; } = "test{0}@test.com";
 
         public static string Next { get; } = "next";
+
+        public static string ThrowErrorAccessDenied { get; } = "test_throw_error_access_denied";
```
Comment (lzc850612) [inline solutions/Virtual-Assistant/src/csharp/skills/tests/CalendarSkillTest/Flow/Strings/Strings.cs]: make all the strings const instead of static

File: solutions/Virtual-Assistant/src/csharp/skills/tests/calendarskilltest/API/Fakes/MockGraphServiceClientGen.cs [hunk 3]
```diff
@@ -1,61 +0,0 @@
-﻿using System.Collections.Generic;
-using System.Threading.Tasks;
```
Comment (lzc850612) [inline solutions/Virtual-Assistant/src/csharp/skills/tests/calendarskilltest/API/Fakes/MockGraphServiceClientGen.cs:2]: why removing this file?

**Review by lzc850612 — CHANGES_REQUESTED** [review]

File: solutions/Virtual-Assistant/src/csharp/skills/tests/calendarskilltest/API/Fakes/MockGraphServiceClientGen.cs (hunk 3 above)
Comment (Theodosia1005) [reply solutions/Virtual-Assistant/src/csharp/skills/tests/calendarskilltest/API/Fakes/MockGraphServiceClientGen.cs:2]: We already change to use new mock service client, so this one will not be used anymore. You can see new mock in MockMSGraphServiceClient.cs

File: solutions/Virtual-Assistant/src/csharp/skills/tests/CalendarSkillTest/Flow/Strings/Strings.cs (hunk 2 above)
Comment (KayMKM) [reply solutions/Virtual-Assistant/src/csharp/skills/tests/CalendarSkillTest/Flow/Strings/Strings.cs]: fixed

**Review by lzc850612 — APPROVED** [review]
