### PR TITLE
[Email] new flow updates

### LINKED ISSUE #1044: Email Skill doesn't show read messages
## Project

Skills

**Language**: C#

## Description
Email Skill doesn't show read messages, instead only unread messages are shown.

## To Reproduce
Mark all messages in your inbox as read and ask for emails

## Expected behavior
This behaviour should be configurable as part of a Skill, in the same way as displaySize.

## Additional context
#1001

### PR DESCRIPTION
**Pull request by DingmaomaoBJTU**
## Description

Fix email part of #1090 Virtual Assistant: confusing prompts in calendar and email
Close #1044 Email Skill doesn't show read messages
Fix email part of #1039 Virtual Assistant: adjust hear/see prompting
Fix email part of #998 Virtual Assistant: change "send" utterance when adding participant for new meeting and email

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the appropriate unit tests
- [x] I have tested any new/updated dialogs using Speech in the emulator to ensure the [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) property is set to enable a high quality speech-first experience and the appropriate [InputHints](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) are set correctly. 
- [x] I have updated related documentation

- [x] A duplicate issue is filed to track future  work.

- [x] All languages have been updated
- [ ] You have tested deployment with your new models

### CODE REVIEW

File: solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/Dialogs/Shared/EmailSkillDialog.cs [hunk 1]
```diff
@@ -462,16 +465,77 @@ protected async Task<DialogTurnResult> ConfirmBeforeSending(WaterfallStepContext
                 };
 
                 var recipientCard = state.Recipients.Count() > 5 ? "ConfirmCard_RecipientMoreThanFive" : "ConfirmCard_RecipientLessThanFive";
```
Comment (bobokids) [inline solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/Dialogs/Shared/EmailSkillDialog.cs]: use DisplayHelper.MaxReadoutNumber?

File: solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/Dialogs/ShowEmail/Resources/ShowEmailResponses.json [hunk 2]
```diff
@@ -11,26 +11,26 @@
...
       }
     ],
     "inputHint": "expectingInput"
   },
   "ReadOutPrompt": {
     "replies": [
       {
-        "speak": "Do you want to hear the content of the first email? I can read out any email for you, just let me know by naming out the subject or from whom.",
-        "text": "Do you want to see the content of the first email? I can show any email for you, just let me know by naming out the subject or from whom."
+        "speak": "Want to know the content of the first email? Let me know if you want to know the next or another email.",
```
Comment (darrenj) [inline solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/Dialogs/ShowEmail/Resources/ShowEmailResponses.json]: "Do you want more detail on the first email? You can also ask about other emails too either by subject or sender"

**Review by darrenj — CHANGES_REQUESTED** [review]

File: solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/Dialogs/Shared/EmailSkillDialog.cs (hunk 1 above)
Comment (DingmaomaoBJTU) [reply solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/Dialogs/Shared/EmailSkillDialog.cs]: Good catch, thanks!~

**Review by darrenj — APPROVED** [review]

**Review by darrenj — APPROVED** [review]
