### PR TITLE
VA: bug fixes and adding new enterprise bot features

### LINKED ISSUE #225: Virtual Assistant does not show confusion message when utterance is unhandled
**Project**

Virtual Assistant

**Description**

When utterance is unrecognized by the dispatcher, the bot does not send a response

### LINKED ISSUE #332: Update VA with new Enterprise Bot start logic and Channel behavior

### PR DESCRIPTION
**Pull request by lauren-mills**
## Description

- Added localized error message for VA
- Added channel support for teams and skype
- Updated response files with MessageFactory logic
- Added confusion message for unhandled intents

## Related Issue

resolves #225 
resolves #332

### CODE REVIEW

File: solutions/Virtual-Assistant/src/csharp/assistant/Dialogs/Escalate/EscalateResponses.cs [hunk 1]
```diff
@@ -10,30 +10,29 @@ namespace VirtualAssistant
...
 
-        public static IMessageActivity SendAcceptingInputReply(ITurnContext turnContext, string text)
+        public class ResponseIds
         {
-            var reply = turnContext.Activity.CreateReply();
-            reply.InputHint = InputHints.AcceptingInput;
-            reply.Text = text;
-
-            return reply;
+            public const string SendEscalationMessage = "sendPhone";
```
Comment (lzc850612) [inline solutions/Virtual-Assistant/src/csharp/assistant/Dialogs/Escalate/EscalateResponses.cs:35]: should this be localized?

File: solutions/Virtual-Assistant/src/csharp/skills/emailskill/.filenesting.json [hunk 2]
```diff
@@ -0,0 +1,22 @@
+{
+  "help": "https://go.microsoft.com/fwlink/?linkid=866610",
```
Comment (lzc850612) [inline solutions/Virtual-Assistant/src/csharp/skills/emailskill/.filenesting.json:2]: Do these files only work if they are put into the folder of different projects?

**Review by lzc850612 — CHANGES_REQUESTED** [review]

File: solutions/Virtual-Assistant/src/csharp/assistant/Dialogs/Escalate/EscalateResponses.cs (hunk 1 above)
Comment (lauren-mills) [reply solutions/Virtual-Assistant/src/csharp/assistant/Dialogs/Escalate/EscalateResponses.cs:35]: It is, this is just the string id of the response

File: solutions/Virtual-Assistant/src/csharp/skills/emailskill/.filenesting.json (hunk 2 above)
Comment (lauren-mills) [reply solutions/Virtual-Assistant/src/csharp/skills/emailskill/.filenesting.json:2]: No, but if I add it to the solution it adds a solution items folder and I think you have to select the file when you click the file nesting button. I wanted the nesting to work even if someone takes a skill project in isolation

File: solutions/Virtual-Assistant/src/csharp/assistant/Dialogs/Escalate/EscalateResponses.cs (hunk 1 above)
Comment (lauren-mills) [reply solutions/Virtual-Assistant/src/csharp/assistant/Dialogs/Escalate/EscalateResponses.cs:35]: It is already, this is just the id for the response. The response is localized in the EscalateStrings.resx

File: solutions/Virtual-Assistant/src/csharp/skills/emailskill/.filenesting.json (hunk 2 above)
Comment (lzc850612) [reply solutions/Virtual-Assistant/src/csharp/skills/emailskill/.filenesting.json:2]: Cool. I've approve the PR. Please look at the build failure because there's a few tests in Todo skill that are failing.

**Review by lzc850612 — APPROVED** [review]
