### PR TITLE
[Calendar] fix calendar regression issue

### LINKED ISSUE #3016: [Calendar] some regression issue
#### What project is affected?
Calendar skill
#### What happens?
1. Welcome message prompt issue. Prompt welcome message before every dialog
image

2. The conversion state is not cleared (so the next conversation will remember state of previous conversation)
image

3. The logic of "intent switch" feature was broken after maindialog change to waterfall dialog, so that some dialog logic went wrong.
image

### PR DESCRIPTION
**Pull request by xhr0804**
### Purpose
*What is the context of this pull request? Why is it being done?*
close #3016  #3027 
### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
1. change the welcome message to new message before each dialog begins for caledar/email/poi/todo skills.
image

2. Add state clear after a dialog end.
image

3. disable "context swith" feature to fix errors.
image

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

File: skills/csharp/calendarskill/Dialogs/MainDialog.cs [hunk 1]
```diff
@@ -217,71 +218,11 @@ protected async Task<bool> InterruptDialogAsync(DialogContext innerDc, Cancellat
 
                                 await innerDc.Context.SendActivityAsync(_templateEngine.GenerateActivityForLocale(CalendarMainResponses.LogOut));
                                 await innerDc.CancelAllDialogsAsync();
-                                await innerDc.BeginDialogAsync(InitialDialogId);
+                                await innerDc.BeginDialogAsync(InitialDialogId, _templateEngine.GenerateActivityForLocale(CalendarMainResponses.CompletedMessage));
                                 interrupted = true;
                                 break;
                             }
                     }
-
```
Comment (bobokids) [inline skills/csharp/calendarskill/Dialogs/MainDialog.cs:225]: why remove this part?

Comment (xhr0804) [reply skills/csharp/calendarskill/Dialogs/MainDialog.cs:225]: This is the entrance of "context swith", we first disable it.

File: skills/csharp/calendarskill/Dialogs/MainDialog.cs [hunk 2]
```diff
@@ -299,9 +239,17 @@ private async Task<DialogTurnResult> IntroStepAsync(WaterfallStepContext stepCon
             else
             {
                 // If bot is in local mode, prompt with intro or continuation message
+                var prompt = stepContext.Options as Activity ?? _templateEngine.GenerateActivityForLocale(CalendarMainResponses.FirstPromptMessage);
+                var state = await _stateAccessor.GetAsync(stepContext.Context, () => new CalendarSkillState());
+                if (state.NewConversation)
```
Comment (lauren-mills) [inline skills/csharp/calendarskill/Dialogs/MainDialog.cs]: When does this property get set to true?

Comment (xhr0804) [reply skills/csharp/calendarskill/Dialogs/MainDialog.cs]: It will be set to true when CalendarSkillState was created. And CalendarSkillState is stored in  conversationState, so it will be set to true when a conversation started or updated.

code: 

```
public class CalendarSkillState
    {
        public UserInformation UserInfo { get; set; } = new UserInformation();
        public bool NewConversation { get; set; } = true;
```

**Review by lzc850612 — APPROVED** [review]

**Review by bobokids — APPROVED** [review]

File: skills/csharp/calendarskill/Dialogs/MainDialog.cs (hunk 2 above)
Comment (lauren-mills) [reply skills/csharp/calendarskill/Dialogs/MainDialog.cs]: A simpler way to do this would be to move the welcome logic to the DefaultActivityHandler in the membersAdded method. Then you wouldn't need to check the state for this.

**Review by lauren-mills — CHANGES_REQUESTED** [review]

**Comment by xhr0804** [comment]
@lauren-mills  If we move WelcomeMessage to DefaultActivityHandler, we will first get a "WelcomMessage” in **membersAdded** and then a "FristPromptMessage" in the **IntroStep** at the begining of conversation.
image
In that case, we may also need to check the state or do other adjustments to the dialog?

File: skills/csharp/calendarskill/Dialogs/MainDialog.cs (hunk 2 above)
Comment (xhr0804) [reply skills/csharp/calendarskill/Dialogs/MainDialog.cs]: If we move WelcomeMessage to DefaultActivityHandler, we will first get a "WelcomMessage” in **membersAdded** and then a "FristPromptMessage" in the **IntroStep** at the begining of conversation.

image

In that case, we may also need to check the state or do other adjustments to the dialog?

Comment (xhr0804) [reply skills/csharp/calendarskill/Dialogs/MainDialog.cs]: @lauren-mills,  I removed the check for state, and added a check "Activity.type == ActivityTypes.ConversationUpdate" to test whether it's a new conversation and should we prompt a "WelcomeMessage" with suggestedActions or a "FirstPromptMessage". This is truly simpler than before.

**Comment by xhr0804** [comment]
@lauren-mills , Hi Lauren, could you please take another look at this PR. You suggested move WelcomeMessage to onMemberAdd and skip the IntroStep when Activity.type==message, but this may cause a infinite loop for dialog like "show next meeting", because in the FinalStep, a new MainDialog will be restarted and will also skip IntroStep and then route.
So I add a check "Activity.type==ActivityType.ConversationUpdate" to check whether we should prompt a "WelcomeMessage" or a "FirstPromptMessage", and remove the "NewConversation" state check. 
Seems it works OK now and is truly simpler than before~

**Review by lauren-mills — APPROVED** [review]
